version: '3.9'

services:
  hodor:
    build:
      context: ./../../
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__PostgreSQL: "Host=postgres;Port=5432;Database=hodor;Username=postgres;Password=postgres"
    ports:
      - "0.0.0.0:8080:8080"
    networks:
      - dev-network
    depends_on:
      postgres:
        condition: service_healthy
